version: '3.6'

services:
    app:
        build:
          context: .
          dockerfile: Dockerfile

        depends_on:
          - db

    db:
        image: mysql:8.0
        restart: always

        ports:
          - "3306:3306"

        environment:
          - MYSQL_DATABSE=doctorly
          - MYSQL_ROOT_PASSWORD=pdoctorlys
        volumes:
          - db:/var/lib/mysql
          - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
    db:
        driver: local